/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import UI_BottomBtnF from "./UI_BottomBtnF";
import UI_topShowUi from "./UI_topShowUi";
import UI_LVPB from "./UI_LVPB";
import UI_txBtn from "./UI_txBtn";
import UI_farmSec from "./UI_farmSec";
import UI_farmSecItem from "./UI_farmSecItem";
import UI_farmItemZw from "./UI_farmItemZw";
import UI_closeBtn from "./UI_closeBtn";
import UI_BadView from "./UI_BadView";
import UI_BadSecView from "./UI_BadSecView";
import UI_closeBtn1 from "./UI_closeBtn1";
import UI_delBtn from "./UI_delBtn";
import UI_addBtn from "./UI_addBtn";
import UI_MaxBtn from "./UI_MaxBtn";
import UI_csBtn from "./UI_csBtn";
import UI_zmBtn from "./UI_zmBtn";
import UI_ShopView from "./UI_ShopView";
import UI_showItem from "./UI_showItem";
import UI_gmBtn from "./UI_gmBtn";
import UI_flyItem from "./UI_flyItem";
import UI_wk3 from "./UI_wk3";
import UI_wk4 from "./UI_wk4";
import UI_wk5 from "./UI_wk5";
import UI_wk6 from "./UI_wk6";
import UI_farmItem from "./UI_farmItem";
import UI_farmMain from "./UI_farmMain";
import UI_FriendView from "./UI_FriendView";
import UI_inviteBtn from "./UI_inviteBtn";
import UI_LevelView from "./UI_LevelView";
import UI_AllinItem from "./UI_AllinItem";
import UI_handState from "./UI_handState";
import UI_UserView from "./UI_UserView";
import UI_ProgressBar1 from "./UI_ProgressBar1";
import UI_Component3 from "./UI_Component3";
import UI_chuchongEff from "./UI_chuchongEff";
import UI_chongziState from "./UI_chongziState";
import UI_EmailView from "./UI_EmailView";
import UI_EmailItem from "./UI_EmailItem";
import UI_EmailSecView from "./UI_EmailSecView";
import UI_AuideView from "./UI_AuideView";
import UI_AuideHand from "./UI_AuideHand";
import UI_wk from "./UI_wk";
import UI_wk1 from "./UI_wk1";
import UI_wk2 from "./UI_wk2";
import UI_sh from "./UI_sh";
import UI_daoshuiCom from "./UI_daoshuiCom";
import UI_farmState from "./UI_farmState";
import UI_AllInView from "./UI_AllInView";
import UI_AllInBig from "./UI_AllInBig";
import UI_oneKeyAddBtn from "./UI_oneKeyAddBtn";
import UI_AlertView from "./UI_AlertView";
import UI_yesBtn from "./UI_yesBtn";
import UI_AwardView from "./UI_AwardView";
import UI_AwardBg from "./UI_AwardBg";
import UI_ptlqBtn from "./UI_ptlqBtn";
import UI_doubleBtn from "./UI_doubleBtn";
import UI_hcBtn from "./UI_hcBtn";
import UI_yellowPoint from "./UI_yellowPoint";
import UI_DealView from "./UI_DealView";
import UI_whitePoint from "./UI_whitePoint";
import UI_DealItem from "./UI_DealItem";
import UI_gmBtn1 from "./UI_gmBtn1";
import UI_DealItem2 from "./UI_DealItem2";
import UI_xjBtn1 from "./UI_xjBtn1";
import UI_shifei from "./UI_shifei";
import UI_shifeiState from "./UI_shifeiState";
import UI_DailyView from "./UI_DailyView";
import UI_DailyItem from "./UI_DailyItem";
import UI_DailyItemBtn from "./UI_DailyItemBtn";
import UI_DailyListItem from "./UI_DailyListItem";
import UI_LiftBtnF from "./UI_LiftBtnF";
import UI_LiftBtn2 from "./UI_LiftBtn2";
import UI_showBtn from "./UI_showBtn";
import UI_hideBtn from "./UI_hideBtn";
import UI_SettingView from "./UI_SettingView";
import UI_settingBtn from "./UI_settingBtn";
import UI_settingBtn1 from "./UI_settingBtn1";
import UI_winnower from "./UI_winnower";
import UI_fangzi from "./UI_fangzi";
import UI_cloud from "./UI_cloud";
import UI_PetView from "./UI_PetView";
import UI_wyBtn from "./UI_wyBtn";
import UI_PetItem from "./UI_PetItem";
import UI_petPb from "./UI_petPb";
import UI_petAdd from "./UI_petAdd";

export default class comBinder {
	public static bindAll():void {
		fgui.UIObjectFactory.setExtension(UI_BottomBtnF.URL, UI_BottomBtnF);
		fgui.UIObjectFactory.setExtension(UI_topShowUi.URL, UI_topShowUi);
		fgui.UIObjectFactory.setExtension(UI_LVPB.URL, UI_LVPB);
		fgui.UIObjectFactory.setExtension(UI_txBtn.URL, UI_txBtn);
		fgui.UIObjectFactory.setExtension(UI_farmSec.URL, UI_farmSec);
		fgui.UIObjectFactory.setExtension(UI_farmSecItem.URL, UI_farmSecItem);
		fgui.UIObjectFactory.setExtension(UI_farmItemZw.URL, UI_farmItemZw);
		fgui.UIObjectFactory.setExtension(UI_closeBtn.URL, UI_closeBtn);
		fgui.UIObjectFactory.setExtension(UI_BadView.URL, UI_BadView);
		fgui.UIObjectFactory.setExtension(UI_BadSecView.URL, UI_BadSecView);
		fgui.UIObjectFactory.setExtension(UI_closeBtn1.URL, UI_closeBtn1);
		fgui.UIObjectFactory.setExtension(UI_delBtn.URL, UI_delBtn);
		fgui.UIObjectFactory.setExtension(UI_addBtn.URL, UI_addBtn);
		fgui.UIObjectFactory.setExtension(UI_MaxBtn.URL, UI_MaxBtn);
		fgui.UIObjectFactory.setExtension(UI_csBtn.URL, UI_csBtn);
		fgui.UIObjectFactory.setExtension(UI_zmBtn.URL, UI_zmBtn);
		fgui.UIObjectFactory.setExtension(UI_ShopView.URL, UI_ShopView);
		fgui.UIObjectFactory.setExtension(UI_showItem.URL, UI_showItem);
		fgui.UIObjectFactory.setExtension(UI_gmBtn.URL, UI_gmBtn);
		fgui.UIObjectFactory.setExtension(UI_flyItem.URL, UI_flyItem);
		fgui.UIObjectFactory.setExtension(UI_wk3.URL, UI_wk3);
		fgui.UIObjectFactory.setExtension(UI_wk4.URL, UI_wk4);
		fgui.UIObjectFactory.setExtension(UI_wk5.URL, UI_wk5);
		fgui.UIObjectFactory.setExtension(UI_wk6.URL, UI_wk6);
		fgui.UIObjectFactory.setExtension(UI_farmItem.URL, UI_farmItem);
		fgui.UIObjectFactory.setExtension(UI_farmMain.URL, UI_farmMain);
		fgui.UIObjectFactory.setExtension(UI_FriendView.URL, UI_FriendView);
		fgui.UIObjectFactory.setExtension(UI_inviteBtn.URL, UI_inviteBtn);
		fgui.UIObjectFactory.setExtension(UI_LevelView.URL, UI_LevelView);
		fgui.UIObjectFactory.setExtension(UI_AllinItem.URL, UI_AllinItem);
		fgui.UIObjectFactory.setExtension(UI_handState.URL, UI_handState);
		fgui.UIObjectFactory.setExtension(UI_UserView.URL, UI_UserView);
		fgui.UIObjectFactory.setExtension(UI_ProgressBar1.URL, UI_ProgressBar1);
		fgui.UIObjectFactory.setExtension(UI_Component3.URL, UI_Component3);
		fgui.UIObjectFactory.setExtension(UI_chuchongEff.URL, UI_chuchongEff);
		fgui.UIObjectFactory.setExtension(UI_chongziState.URL, UI_chongziState);
		fgui.UIObjectFactory.setExtension(UI_EmailView.URL, UI_EmailView);
		fgui.UIObjectFactory.setExtension(UI_EmailItem.URL, UI_EmailItem);
		fgui.UIObjectFactory.setExtension(UI_EmailSecView.URL, UI_EmailSecView);
		fgui.UIObjectFactory.setExtension(UI_AuideView.URL, UI_AuideView);
		fgui.UIObjectFactory.setExtension(UI_AuideHand.URL, UI_AuideHand);
		fgui.UIObjectFactory.setExtension(UI_wk.URL, UI_wk);
		fgui.UIObjectFactory.setExtension(UI_wk1.URL, UI_wk1);
		fgui.UIObjectFactory.setExtension(UI_wk2.URL, UI_wk2);
		fgui.UIObjectFactory.setExtension(UI_sh.URL, UI_sh);
		fgui.UIObjectFactory.setExtension(UI_daoshuiCom.URL, UI_daoshuiCom);
		fgui.UIObjectFactory.setExtension(UI_farmState.URL, UI_farmState);
		fgui.UIObjectFactory.setExtension(UI_AllInView.URL, UI_AllInView);
		fgui.UIObjectFactory.setExtension(UI_AllInBig.URL, UI_AllInBig);
		fgui.UIObjectFactory.setExtension(UI_oneKeyAddBtn.URL, UI_oneKeyAddBtn);
		fgui.UIObjectFactory.setExtension(UI_AlertView.URL, UI_AlertView);
		fgui.UIObjectFactory.setExtension(UI_yesBtn.URL, UI_yesBtn);
		fgui.UIObjectFactory.setExtension(UI_AwardView.URL, UI_AwardView);
		fgui.UIObjectFactory.setExtension(UI_AwardBg.URL, UI_AwardBg);
		fgui.UIObjectFactory.setExtension(UI_ptlqBtn.URL, UI_ptlqBtn);
		fgui.UIObjectFactory.setExtension(UI_doubleBtn.URL, UI_doubleBtn);
		fgui.UIObjectFactory.setExtension(UI_hcBtn.URL, UI_hcBtn);
		fgui.UIObjectFactory.setExtension(UI_yellowPoint.URL, UI_yellowPoint);
		fgui.UIObjectFactory.setExtension(UI_DealView.URL, UI_DealView);
		fgui.UIObjectFactory.setExtension(UI_whitePoint.URL, UI_whitePoint);
		fgui.UIObjectFactory.setExtension(UI_DealItem.URL, UI_DealItem);
		fgui.UIObjectFactory.setExtension(UI_gmBtn1.URL, UI_gmBtn1);
		fgui.UIObjectFactory.setExtension(UI_DealItem2.URL, UI_DealItem2);
		fgui.UIObjectFactory.setExtension(UI_xjBtn1.URL, UI_xjBtn1);
		fgui.UIObjectFactory.setExtension(UI_shifei.URL, UI_shifei);
		fgui.UIObjectFactory.setExtension(UI_shifeiState.URL, UI_shifeiState);
		fgui.UIObjectFactory.setExtension(UI_DailyView.URL, UI_DailyView);
		fgui.UIObjectFactory.setExtension(UI_DailyItem.URL, UI_DailyItem);
		fgui.UIObjectFactory.setExtension(UI_DailyItemBtn.URL, UI_DailyItemBtn);
		fgui.UIObjectFactory.setExtension(UI_DailyListItem.URL, UI_DailyListItem);
		fgui.UIObjectFactory.setExtension(UI_LiftBtnF.URL, UI_LiftBtnF);
		fgui.UIObjectFactory.setExtension(UI_LiftBtn2.URL, UI_LiftBtn2);
		fgui.UIObjectFactory.setExtension(UI_showBtn.URL, UI_showBtn);
		fgui.UIObjectFactory.setExtension(UI_hideBtn.URL, UI_hideBtn);
		fgui.UIObjectFactory.setExtension(UI_SettingView.URL, UI_SettingView);
		fgui.UIObjectFactory.setExtension(UI_settingBtn.URL, UI_settingBtn);
		fgui.UIObjectFactory.setExtension(UI_settingBtn1.URL, UI_settingBtn1);
		fgui.UIObjectFactory.setExtension(UI_winnower.URL, UI_winnower);
		fgui.UIObjectFactory.setExtension(UI_fangzi.URL, UI_fangzi);
		fgui.UIObjectFactory.setExtension(UI_cloud.URL, UI_cloud);
		fgui.UIObjectFactory.setExtension(UI_PetView.URL, UI_PetView);
		fgui.UIObjectFactory.setExtension(UI_wyBtn.URL, UI_wyBtn);
		fgui.UIObjectFactory.setExtension(UI_PetItem.URL, UI_PetItem);
		fgui.UIObjectFactory.setExtension(UI_petPb.URL, UI_petPb);
		fgui.UIObjectFactory.setExtension(UI_petAdd.URL, UI_petAdd);
	}
}